application: food-ing
version: 1
runtime: php
api_version: 1
threadsafe: true

handlers:
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: \1
  mime_type: (image/jpg|image/png)
  upload: (.*\.(bmp|gif|ico|jpeg|jpg|png))

- url: /css
  static_dir: css

- url : /image
  static_dir: image

- url : /js
  static_dir: js

- url: /.*
  script: banana2.html